# ------------------------------------------------ #
# Note: this file originates in template-terraform #
# ------------------------------------------------ #

version: 2
updates:
  - package-ecosystem: terraform
    open-pull-requests-limit: 10
    directory: /
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    schedule:
      interval: daily
      time: "10:00"
      timezone: America/Toronto
