additional:
  - "terraform-*"

files:
  - "!README.md"
  - "!docs/README.md"
  - "!colophon.yml"
  - "!**/template-sync.yml"
  - "!.github/dependabot.yml"
  - .github/dependabot-template.yml: .github/dependabot.yml
