# ------------------------------------------------ #
# Note: this file originates in template-terraform #
# ------------------------------------------------ #

services:
  # ---- mega-linter ---- #
  lint:
    profiles: ["dev"]
    image: oxsecurity/megalinter-terraform:v7.2.1
    volumes:
      - ./:/tmp/lint
    environment:
      MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
      REPORT_OUTPUT_FOLDER: none
      VALIDATE_ALL_CODEBASE: true

  # ---- main container ---- #
  terraform:
    profiles: ["app"]
    image: hashicorp/terraform:1.5.5
    working_dir: /usr/src/terraform
    entrypoint: terraform
    tty: true
    volumes:
      - ./:/usr/src/terraform
      - ${GOOGLE_CREDENTIALS}:${GOOGLE_CREDENTIALS}
    environment:
      - GITHUB_TOKEN
      - GOOGLE_CREDENTIALS
      - CLOUDFLARE_API_TOKEN
      - TF_TOKEN_app_terraform_io=${TF_TOKEN}

      - TF_VAR_SHARED_TF_TOKEN
      - TF_VAR_SHARED_GH_TOKEN
      - TF_VAR_SHARED_NPM_TOKEN
      - TF_VAR_SHARED_DOCKER_TOKEN
      - TF_VAR_SHARED_TOKEN_ROTATION
      - TF_VAR_SHARED_CLOUDFLARE_TOKEN

  # ---- readme generator ---- #
  readme:
    image: pandoc/minimal:2.19
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml
