# ------------------------------------------------ #
# Note: this file originates in template-terraform #
# ------------------------------------------------ #

services:
  # ---- mega-linter ---- #
  lint:
    profiles: ["dev"]
    image: oxsecurity/megalinter-terraform:v8.3.0
    volumes:
      - ./:/tmp/lint
    environment:
      MEGALINTER_CONFIG: .github/linters/.mega-linter.yml
      REPORT_OUTPUT_FOLDER: none
      VALIDATE_ALL_CODEBASE: true

  # ---- main container ---- #
  terraform:
    profiles: ["app"]
    image: hashicorp/terraform:1.10.3
    working_dir: /usr/src/terraform
    entrypoint: terraform
    tty: true
    volumes:
      - ./:/usr/src/terraform
    environment:
      # provider variables
      - GITHUB_TOKEN=${TOKEN_GITHUB}
      - CLOUDFLARE_API_TOKEN=${TOKEN_CLOUDFLARE}
      - TF_TOKEN_app_terraform_io=${TOKEN_TERRAFORM}

      # module variables
      - TF_VAR_TOKEN_1PASSWORD
      - TF_VAR_TOKEN_ROTATION

  # ---- readme generator ---- #
  readme:
    image: pandoc/minimal:2.19
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml
