# ------------------------------------------------ #
# Note: this file originates in template-terraform #
# ------------------------------------------------ #

name: pull_request

on: pull_request

permissions: read-all

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/pull-request-terraform.yml@master
    secrets: inherit
    permissions:
      pull-requests: write
