# ------------------------------------------------ #
# Note: this file originates in template-terraform #
# ------------------------------------------------ #

name: push

on:
  - push
  - workflow_dispatch

permissions: read-all

jobs:
  main:
    uses: ahmadnassri/actions/.github/workflows/push-terraform.yml@master
    secrets: inherit
    permissions:
      contents: write
      statuses: write
      pull-requests: write
